services:
  - type: web
    name: reflex-royale
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: TRUST_PROXY
        value: "true"
      - key: PORT
        value: 3000
      - key: MONGODB_URI
        sync: false
      - key: SESSION_SECRET
        sync: false
