const assert = require("assert/strict");
const fs = require("fs");
const path = require("node:path");
const test = require("node:test");

function loadServerModule() {
  delete require.cache[require.resolve("../server")];
  return require("../server");
}

function findRoutePath(appInstance, routePath) {
  const layer = appInstance._router.stack.find((entry) => entry.route && entry.route.path === routePath);
  if (!layer) {
    throw new Error(`Route not found: ${routePath}`);
  }

  return layer.route.stack[0].handle;
}

async function invoke(handler, { session = null, acceptsHtml = false } = {}) {
  const req = {
    session,
    accepts(value) {
      return acceptsHtml && value === "html";
    },
    originalUrl: "/test"
  };

  const res = {
    statusCode: 200,
    redirectedTo: null,
    sentFile: null,
    jsonPayload: null,
    status(code) {
      this.statusCode = code;
      return this;
    },
    redirect(url) {
      this.redirectedTo = url;
      return this;
    },
    sendFile(filePath) {
      this.sentFile = filePath;
      return this;
    },
    json(payload) {
      this.jsonPayload = payload;
      return this;
    }
  };

  await handler(req, res);
  return res;
}

test("guest can access dashboard and game routes", async () => {
  const { createApp } = loadServerModule();
  const app = createApp({ useSessionStore: false });
  const dashboard = findRoutePath(app, "/dashboard");
  const navigate = findRoutePath(app, "/navigate");
  const local = findRoutePath(app, "/local");
  const online = findRoutePath(app, "/online");

  const dashboardRes = await invoke(dashboard);
  const navigateRes = await invoke(navigate);
  const localRes = await invoke(local);
  const onlineRes = await invoke(online);

  assert.ok(dashboardRes.sentFile?.includes("dashboard.html"));
  assert.ok(navigateRes.sentFile?.includes("index.html"));
  assert.ok(localRes.sentFile?.includes("game-local.html"));
  assert.ok(onlineRes.sentFile?.includes("game-remote.html"));
});

test("session endpoint exposes guest state and user state", async () => {
  const { createApp } = loadServerModule();
  const app = createApp({ useSessionStore: false });
  const sessionHandler = findRoutePath(app, "/api/auth/session");

  const guestRes = await invoke(sessionHandler);
  assert.equal(guestRes.jsonPayload.authenticated, false);
  assert.equal(guestRes.jsonPayload.user, null);

  const userRes = await invoke(sessionHandler, { session: { user: { id: "1", username: "Ada" } } });
  assert.equal(userRes.jsonPayload.authenticated, true);
  assert.equal(userRes.jsonPayload.user.username, "Ada");
});

test("ui-lab imports only direct thegridcn components", () => {
  const pageSource = fs.readFileSync(require.resolve("../src/app/ui-lab/page.tsx"), "utf8");
  const clientSource = fs.readFileSync(require.resolve("../src/app/ui-lab/ui-lab-client.tsx"), "utf8");
  const gridSource = fs.readFileSync(require.resolve("../src/components/grid.tsx"), "utf8");
  const layoutSource = fs.readFileSync(require.resolve("../src/app/ui-lab/layout.tsx"), "utf8");
  const atmosphereSource = fs.readFileSync(require.resolve("../src/app/ui-lab/atmosphere.ts"), "utf8");
  const selectSource = fs.readFileSync(require.resolve("../src/components/thegridcn/select.tsx"), "utf8");
  const themeSource = fs.readFileSync(require.resolve("../src/components/thegridcn-theme.css"), "utf8");
  const intensitySource = fs.readFileSync(require.resolve("../src/components/thegridcn-intensity.css"), "utf8");
  const nodemonSource = fs.readFileSync(require.resolve("../nodemon.json"), "utf8");

  assert.match(pageSource, /from "next\/headers"/);
  assert.match(pageSource, /cookies\(\)/);
  assert.match(pageSource, /initialTheme/);
  assert.match(pageSource, /initialIntensity/);
  assert.match(pageSource, /initialAtmosphere/);
  assert.doesNotMatch(pageSource, /localStorage\.getItem/);
  assert.match(pageSource, /UiLabClient/);

  assert.match(clientSource, /@\/components\/thegridcn\/button/);
  assert.match(clientSource, /@\/components\/thegridcn\/card/);
  assert.match(clientSource, /@\/components\/thegridcn\/toast/);
  assert.match(clientSource, /@\/components\/thegridcn\/dropdown/);
  assert.match(clientSource, /@\/components\/thegridcn\/dialog/);
  assert.match(clientSource, /@\/components\/thegridcn\/table/);
  assert.match(clientSource, /@\/components\/thegridcn\/input/);
  assert.match(clientSource, /@\/components\/thegridcn\/badge/);
  assert.match(clientSource, /@\/components\/thegridcn\/select/);
  assert.match(clientSource, /@\/components\/grid/);
  assert.match(clientSource, /@\/components\/theme/);
  assert.match(clientSource, /\.\/atmosphere/);
  assert.match(clientSource, /ui-lab-background/);
  assert.match(clientSource, /ui-lab-grid-3d/);
  assert.match(clientSource, /ui-lab-dashboard/);
  assert.match(clientSource, /ui-lab-control-panel/);
  assert.match(clientSource, /ui-lab-atmosphere-panel/);
  assert.match(clientSource, /ComponentSpecimen/);
  assert.match(clientSource, /cameraAnimation=\{!isIntensityNone\}/);
  assert.match(clientSource, /sway=\{atmosphere\.sway\}/);
  assert.match(clientSource, /swaySpeed=\{atmosphere\.swaySpeed\}/);
  assert.match(clientSource, /particleCount=\{atmosphere\.particleCount\}/);
  assert.match(clientSource, /beamThickness=\{atmosphere\.beamThickness\}/);
  assert.match(clientSource, /data-theme=\{theme\}/);
  assert.match(clientSource, /data-tron-intensity=\{intensity\}/);
  assert.ok(clientSource.includes('localStorage.setItem("ui-lab-theme"'));
  assert.ok(clientSource.includes('localStorage.setItem("ui-lab-intensity"'));
  assert.match(clientSource, /document\.cookie =/);
  assert.match(clientSource, /document\.documentElement\.dataset\.theme = theme/);
  assert.match(clientSource, /document\.documentElement\.dataset\.tronIntensity = intensity/);
  assert.match(clientSource, /SelectTrigger/);
  assert.match(clientSource, /SelectContent/);
  assert.match(clientSource, /SelectItem/);
  assert.match(clientSource, /Component: Button/);
  assert.match(clientSource, /Component: Badge/);
  assert.match(clientSource, /Component: Input/);
  assert.match(clientSource, /Component: Select/);
  assert.match(clientSource, /Component: Dropdown/);
  assert.match(clientSource, /Component: Dialog/);
  assert.match(clientSource, /Component: Toast/);
  assert.match(clientSource, /Component: Table/);
  assert.match(clientSource, /Component: Card/);
  assert.match(clientSource, /Switch to \{isAres \? "Tron" : "Ares"\}/);
  assert.match(clientSource, /INTENSITY_OPTIONS/);
  assert.match(clientSource, /Intensity: \{intensity\}/);
  assert.match(clientSource, /ATMOSPHERE_PRESET_OPTIONS/);
  assert.match(clientSource, /RangeField/);
  assert.match(clientSource, /Grid Sway/);
  assert.match(clientSource, /Drift Speed/);
  assert.match(clientSource, /Background Visibility/);
  assert.match(clientSource, /Particle Density/);
  assert.match(clientSource, /Beam Strength/);
  assert.match(clientSource, /ui-lab-grid-sway-duration/);
  assert.match(clientSource, /max=\{500\}/);
  assert.match(gridSource, /DEFAULT_HORIZON_TARGET/);
  assert.match(gridSource, /DEFAULT_CAMERA_POSITION: Vector3Tuple = \[0, 7\.2, 28\]/);
  assert.match(gridSource, /camera\.position\.set\(\.\.\.position\)/);
  assert.match(gridSource, /particleCount = 180/);
  assert.match(gridSource, /beamThickness = 0\.045/);
  assert.match(gridSource, /cylinderGeometry args=\{\[thickness, thickness, BEAM_HEIGHT, 8\]\}/);
  assert.match(gridSource, /opacity = 0\.42/);
  assert.match(gridSource, /function SceneSway/);
  assert.match(gridSource, /rotation\.z = Math\.sin\(time \* 0\.8\)/);
  assert.match(gridSource, /rotation\.y = Math\.sin\(time \* 0\.5\)/);
  assert.match(gridSource, /cameraAnimation \? <CameraController/);
  assert.match(gridSource, /<StaticCamera position=\{cameraPosition\} target=\{cameraTarget\} \/>/);
  assert.doesNotMatch(gridSource, /Math\.cos\(time\)/);
  assert.doesNotMatch(gridSource, /camera\.position\.z = Math\.sin\(time\)/);
  assert.match(clientSource, /fixed background viewport/);
  assert.match(selectSource, /data-slot="select-trigger"/);
  assert.match(selectSource, /data-slot="select-content"/);
  assert.match(selectSource, /data-slot="select-item"/);
  assert.match(intensitySource, /select-trigger/);
  assert.match(intensitySource, /select-content/);
  assert.match(intensitySource, /select-item/);
  assert.match(intensitySource, /prefers-reduced-motion/);
  assert.match(layoutSource, /@\/components\/thegridcn-theme\.css/);
  assert.match(layoutSource, /@\/components\/thegridcn-intensity\.css/);
  assert.match(themeSource, /\[data-theme="tron"\]/);
  assert.match(themeSource, /--glow:/);
  assert.match(themeSource, /--glow-muted:/);
  assert.match(intensitySource, /--ui-lab-grid-opacity: 0\.48/);
  assert.match(intensitySource, /--ui-lab-grid-opacity: 0\.58/);
  assert.match(intensitySource, /--ui-lab-grid-opacity: 0\.72/);
  assert.match(intensitySource, /--ui-lab-grid-opacity-multiplier: 1/);
  const uiLabCssSource = fs.readFileSync(require.resolve("../src/app/ui-lab/ui-lab.css"), "utf8");
  assert.match(uiLabCssSource, /@keyframes ui-lab-grid-sway/);
  assert.match(uiLabCssSource, /animation: ui-lab-grid-sway var\(--ui-lab-grid-sway-duration, 18s\) ease-in-out infinite alternate/);
  assert.match(uiLabCssSource, /ui-lab-atmosphere-panel/);
  assert.match(uiLabCssSource, /ui-lab-range-field/);
  assert.match(uiLabCssSource, /ui-lab-range/);
  assert.match(uiLabCssSource, /ui-lab-grid-sway-x/);
  assert.match(uiLabCssSource, /ui-lab-grid-sway-y/);
  assert.match(nodemonSource, /"\.next"/);
  assert.match(nodemonSource, /"server\.js"/);

  assert.match(atmosphereSource, /DEFAULT_ATMOSPHERE/);
  assert.match(atmosphereSource, /applyAtmospherePreset/);
  assert.match(atmosphereSource, /parseAtmosphere/);

  assert.doesNotMatch(pageSource, /@\/components\/ui\//);
  assert.doesNotMatch(pageSource, /@\/components\/button/);
  assert.doesNotMatch(pageSource, /@\/components\/card/);
  assert.doesNotMatch(pageSource, /@\/components\/dialog/);
  assert.doesNotMatch(pageSource, /@\/components\/dropdown-menu/);
  assert.doesNotMatch(pageSource, /@\/components\/table/);
  assert.doesNotMatch(pageSource, /@\/components\/input/);
  assert.doesNotMatch(pageSource, /@\/components\/badge/);
});

test("dashboard page renders a command center layout", () => {
  const dashboardSource = fs.readFileSync(require.resolve("../src/app/dashboard/page.tsx"), "utf8");
  const tabsSource = fs.readFileSync(require.resolve("../src/components/app/dashboard-tabs.tsx"), "utf8");
  const globalsSource = fs.readFileSync(require.resolve("../src/app/globals.css"), "utf8");
  const dashboardStylesSource = fs.readFileSync(require.resolve("../src/app/dashboard/dashboard.css"), "utf8");

  assert.match(dashboardSource, /DashboardTabs/);
  assert.match(dashboardSource, /dashboard-page/);
  assert.match(dashboardSource, /CircuitBackground/);
  assert.match(dashboardSource, /animated=\{false\}/);
  assert.doesNotMatch(dashboardSource, /GridBackground/);
  assert.match(tabsSource, /AuthMenu/);
  assert.doesNotMatch(tabsSource, /dashboard-topbar/);
  assert.match(tabsSource, /WireframeDottedGlobe/);
  assert.match(tabsSource, /key=\{`arena-earth-\$\{themeCommand\}-\$\{customThemeColor\}`\}/);
  assert.match(tabsSource, /arenaActive/);
  assert.match(tabsSource, /animated=\{arenaActive && visualAnimationsEnabled\}/);
  assert.match(tabsSource, /kind="earth"/);
  assert.match(tabsSource, /href="\/navigate"/);
  assert.match(tabsSource, /Navigation/);
  assert.match(tabsSource, /Play Now/);
  assert.match(tabsSource, /Analytics/);
  assert.match(tabsSource, /Recent Avg/);
  assert.match(tabsSource, /Win Rate/);
  assert.match(tabsSource, /Lifetime Avg/);
  assert.match(tabsSource, /Current Streak/);
  assert.match(tabsSource, /Best Streak/);
  assert.match(tabsSource, /Games Played/);
  assert.match(tabsSource, /False Starts/);
  assert.match(tabsSource, /Time Played/);
  assert.match(tabsSource, /Reactions/);
  assert.match(tabsSource, /Online only/);
  assert.match(tabsSource, /Visuals/);
  assert.match(tabsSource, /Sound/);
  assert.match(tabsSource, /Personalization/);
  assert.match(tabsSource, /Paintbrush/);
  assert.match(tabsSource, /Music2/);
  assert.match(tabsSource, /UserRound/);
  assert.match(tabsSource, /data-section-id="visuals"/);
  assert.match(tabsSource, /data-section-id="sound"/);
  assert.match(tabsSource, /data-section-id="personalization"/);
  assert.match(tabsSource, /Top Players/);
  assert.match(tabsSource, /Recent Matches/);
  assert.match(tabsSource, /Avg Reaction/);
  assert.match(tabsSource, /No recent matches logged/);
  assert.match(tabsSource, /General Settings/);
  assert.match(tabsSource, /Visual Presets/);
  assert.match(tabsSource, /Disable Animations/);
  assert.match(tabsSource, /VISUAL_ANIMATIONS_KEY/);
  assert.match(tabsSource, /dashboard-visual-preset-metrics/);
  assert.match(tabsSource, /Advanced Settings/);
  assert.match(tabsSource, /Calm/);
  assert.match(tabsSource, /Balanced/);
  assert.match(tabsSource, /Electric/);
  assert.match(tabsSource, /Scene Sway/);
  assert.match(tabsSource, /Particle Density/);
  assert.match(tabsSource, /Beam Width/);
  assert.match(tabsSource, /ui-lab-atmosphere/);
  assert.match(tabsSource, /Audio Settings/);
  assert.match(tabsSource, /dashboard-sound-player-slot/);
  assert.match(tabsSource, /reflexRoyalePreferredKey/);
  assert.match(tabsSource, /reflexRoyaleCustomThemeColor/);
  assert.doesNotMatch(tabsSource, /type="color"/);
  assert.match(tabsSource, /THEME: COMMAND/);
  assert.match(tabsSource, /THEME_COMMANDS/);
  assert.match(tabsSource, /VULCAN/);
  assert.match(tabsSource, /APOLLO/);
  assert.match(tabsSource, /GAIA/);
  assert.match(tabsSource, /TabsList/);
  assert.match(tabsSource, /TooltipContent/);
  assert.match(tabsSource, /dashboard-theme-indicator/);
  assert.doesNotMatch(tabsSource, /title=\{theme === "custom"/);
  assert.match(tabsSource, /Preferred Buzzer Matrix/);
  assert.match(tabsSource, /Theme/);
  assert.match(tabsSource, /OLYMPUS/);
  assert.doesNotMatch(tabsSource, /name: "CUSTOM"/);
  assert.match(tabsSource, /ares/);
  assert.match(tabsSource, /Glow Intensity/);
  assert.match(tabsSource, /Master Volume/);
  assert.match(tabsSource, /Mix/);
  assert.match(tabsSource, /Audio Catalog/);
  assert.match(tabsSource, /dashboard-audio-catalog-search/);
  assert.match(tabsSource, /dashboard-audio-catalog-row/);
  assert.match(tabsSource, /SelectItem value="default"/);
  assert.match(tabsSource, /SelectItem value="custom"/);
  assert.match(tabsSource, /SelectItem value="lobby"/);
  assert.match(tabsSource, /SelectItem value="battle"/);
  assert.match(tabsSource, /useState/);
  assert.match(tabsSource, /dashboard-arena-card/);
  assert.match(tabsSource, /fluorescent-title/);
  assert.match(globalsSource, /\.\/dashboard\/dashboard\.css/);
  assert.match(globalsSource, /@keyframes fluorescent-title-pulse/);
  assert.match(globalsSource, /\.fluorescent-title/);
  assert.doesNotMatch(globalsSource, /\.dashboard-arena-card/);
  assert.match(dashboardStylesSource, /\.dashboard-arena-card/);
  assert.match(dashboardStylesSource, /\.dashboard-play-grid/);
  assert.match(dashboardStylesSource, /\.dashboard-circuit-background/);
  assert.match(dashboardStylesSource, /\.dashboard-arena-card__earth/);
  assert.match(dashboardStylesSource, /\.dashboard-navigation-button/);
  assert.match(dashboardStylesSource, /\.dashboard-analytics-section/);
  assert.match(dashboardStylesSource, /\.dashboard-analytics-grid/);
  assert.match(dashboardStylesSource, /\.dashboard-recent-matches-card/);
  assert.match(dashboardStylesSource, /\.dashboard-recent-matches-content/);
  assert.match(dashboardStylesSource, /\.dashboard-personalization-section/);
  assert.match(dashboardStylesSource, /\.dashboard-preferred-key/);
  assert.match(dashboardStylesSource, /\.dashboard-theme-option/);
  assert.match(dashboardStylesSource, /--dashboard-theme-option-color/);
  assert.match(dashboardStylesSource, /\.dashboard-theme-tab/);
  assert.match(dashboardStylesSource, /grid-template-columns: repeat\(8, minmax\(0, 1fr\)\)/);
  assert.match(dashboardStylesSource, /top: -4\.25rem/);
  assert.doesNotMatch(dashboardStylesSource, /\.dashboard-custom-theme-picker/);
  assert.match(dashboardStylesSource, /\.dashboard-theme-indicator/);
  assert.match(dashboardStylesSource, /\.dashboard-theme-tooltip/);
  assert.doesNotMatch(dashboardStylesSource, /clip-path: polygon\(25% 3%, 75% 3%, 100% 50%, 75% 97%, 25% 97%, 0 50%\)/);
  assert.doesNotMatch(dashboardStylesSource, /dashboard-custom-theme-apply/);
  assert.match(dashboardStylesSource, /--dashboard-panel-height: calc\(100svh - \(var\(--dashboard-chrome-y\) \* 2\)\)/);
  assert.match(dashboardStylesSource, /box-shadow 700ms ease-out/);
  assert.match(dashboardStylesSource, /height: var\(--dashboard-panel-height\)/);
  assert.match(dashboardStylesSource, /min-height: 0/);
  assert.match(dashboardStylesSource, /height: calc\(100% - 2\.25rem\)/);
});

test("navigate page renders orbital route selection", () => {
  const landingSource = fs.readFileSync(require.resolve("../src/app/page.tsx"), "utf8");
  const navigateSource = fs.readFileSync(require.resolve("../src/app/navigate/page.tsx"), "utf8");
  const sceneSource = fs.readFileSync(require.resolve("../src/components/app/navigation-scene.tsx"), "utf8");
  const navigateGridBackdropSource = fs.readFileSync(require.resolve("../src/components/app/navigate-grid-backdrop.tsx"), "utf8");
  const globeSource = fs.readFileSync(require.resolve("../src/components/app/wireframe-dotted-globe.tsx"), "utf8");
  const locationSource = fs.readFileSync(require.resolve("../src/components/thegridcn/location-display.tsx"), "utf8");
  const reticleSource = fs.readFileSync(require.resolve("../src/components/thegridcn/reticle.tsx"), "utf8");
  const globalsSource = fs.readFileSync(require.resolve("../src/app/globals.css"), "utf8");
  const navigateStylesSource = fs.readFileSync(require.resolve("../src/app/navigate/navigate.css"), "utf8");
  const layoutSource = fs.readFileSync(require.resolve("../src/app/layout.tsx"), "utf8");

  assert.match(landingSource, /playNowHref = "\/navigate"/);
  assert.match(landingSource, /fluorescent-title/);
  assert.match(navigateSource, /NavigationScene/);
  assert.match(navigateSource, /getCurrentUser/);
  assert.doesNotMatch(navigateSource, /AuthMenu/);
  assert.match(sceneSource, /CircuitBackground/);
  assert.match(sceneSource, /fluorescent-title/);
  assert.match(sceneSource, /WireframeDottedGlobe/);
  assert.match(globeSource, /VISUAL_ANIMATIONS_KEY/);
  assert.match(globeSource, /reflexRoyaleVisualAnimationsEnabled/);
  assert.match(globeSource, /visualAnimationsEnabled/);
  assert.match(globeSource, /maxFps = 30/);
  assert.match(globeSource, /minFrameDuration = 1000 \/ Math\.max\(1, maxFps\)/);
  assert.match(sceneSource, /maxFps=\{16\}/);
  assert.doesNotMatch(sceneSource, /DerezTimer/);
  assert.match(sceneSource, /LocationDisplay/);
  assert.match(sceneSource, /Reticle/);
  assert.match(sceneSource, /variant="scanning"/);
  assert.doesNotMatch(sceneSource, /navigate-border-hud__readout/);
  assert.match(sceneSource, /MoonNode/);
  assert.match(sceneSource, /navigate-earth/);
  assert.match(sceneSource, /navigate-moon/);
  assert.match(sceneSource, /NavigateGridBackdrop/);
  assert.match(navigateGridBackdropSource, /const THEME_KEY = "ui-lab-theme"/);
  assert.match(navigateGridBackdropSource, /function isTheme/);
  assert.match(navigateGridBackdropSource, /readActiveTheme/);
  assert.match(navigateGridBackdropSource, /ThemeProvider theme=\{theme\}/);
  assert.match(navigateGridBackdropSource, /data-grid-theme=\{theme\}/);
  assert.match(navigateGridBackdropSource, /VISUAL_PREFERENCES_CHANGED_EVENT/);
  assert.doesNotMatch(navigateGridBackdropSource, /ThemeProvider theme="tron"/);
  assert.doesNotMatch(sceneSource, /SimplePlanet/);
  assert.match(sceneSource, /navigate-route-stack/);
  assert.match(sceneSource, /href="\/local"/);
  assert.match(sceneSource, /canPlayOnline/);
  assert.match(sceneSource, /href="\/online"/);
  assert.match(sceneSource, /href=\{canPlayOnline \? "\/dashboard" : "\/"\}/);
  assert.match(sceneSource, /Dashboard/);
  assert.match(sceneSource, /Exit/);
  assert.match(sceneSource, /navigate-tab--exit/);
  assert.match(sceneSource, /Create an account to unlock online play/);
  assert.match(sceneSource, /aria-disabled="true"/);
  assert.match(globalsSource, /\.\/navigate\/navigate\.css/);
  assert.doesNotMatch(globalsSource, /\.navigate-circuit-bg/);
  assert.match(navigateStylesSource, /\.navigate-circuit-bg/);
  assert.match(navigateStylesSource, /\.navigate-border-hud/);
  assert.doesNotMatch(globalsSource, /\.navigate-derez-timer/);
  assert.match(navigateStylesSource, /\.navigate-location-display/);
  assert.match(navigateStylesSource, /\.navigate-body-reticle/);
  assert.match(sceneSource, /navigate-earth-viewport-layer/);
  assert.match(sceneSource, /navigate-earth-anchor/);
  assert.match(navigateStylesSource, /\.navigate-earth-viewport-layer/);
  assert.match(navigateStylesSource, /\.navigate-earth-anchor/);
  assert.match(navigateStylesSource, /mask-image: linear-gradient/);
  assert.match(navigateStylesSource, /\.navigate-grid-backdrop/);
  assert.doesNotMatch(navigateStylesSource, /\.navigate-simple-planet/);
  assert.match(sceneSource, /kind="moon"/);
  assert.match(navigateStylesSource, /\.navigate-globe-canvas/);
  assert.match(navigateStylesSource, /\.navigate-moon__orbit/);
  assert.match(navigateStylesSource, /\.navigate-route-line--online/);
  assert.match(navigateStylesSource, /\.navigate-tab--disabled/);
  assert.match(navigateStylesSource, /\.navigate-tooltip/);
  assert.match(navigateStylesSource, /\.navigate-tab:hover/);
  assert.match(navigateStylesSource, /:has\(\.navigate-tab:hover\)/);
  assert.match(globeSource, /projectVisiblePoint/);
  assert.match(globeSource, /natural-earth-geojson/);
  assert.match(globeSource, /prefers-reduced-motion/);
  assert.match(locationSource, /LocationDisplay/);
  assert.match(reticleSource, /variant\?: "default" \| "locked" \| "scanning"/);
  assert.match(layoutSource, /AudioController/);
});

test("game routes render inside the modern game shell", () => {
  const localPageSource = fs.readFileSync(require.resolve("../src/app/local/page.tsx"), "utf8");
  const onlinePageSource = fs.readFileSync(require.resolve("../src/app/online/page.tsx"), "utf8");
  const shellSource = fs.readFileSync(require.resolve("../src/components/app/game-page-shell.tsx"), "utf8");
  const tabsSource = fs.readFileSync(require.resolve("../src/components/app/dashboard-tabs.tsx"), "utf8");
  const legacyShellSource = fs.readFileSync(require.resolve("../src/components/legacy-game-shell.tsx"), "utf8");
  const localRendererSource = fs.readFileSync(require.resolve("../public/js/UIRenderer.js"), "utf8");
  const localPaletteSource = fs.readFileSync(require.resolve("../public/js/localThemePalette.js"), "utf8");
  const gameCssSource = fs.readFileSync(require.resolve("../public/game.css"), "utf8");
  const buttonSource = fs.readFileSync(require.resolve("../src/components/thegridcn/button.tsx"), "utf8");
  const audioSource = fs.readFileSync(require.resolve("../src/components/app/audio-controller.tsx"), "utf8");
  const audioLibSource = fs.readFileSync(require.resolve("../src/lib/audio.ts"), "utf8");
  const audioRoutesSource = fs.readFileSync(require.resolve("../routes/audio.js"), "utf8");
  const audioModelSource = fs.readFileSync(require.resolve("../models/AudioTrack.js"), "utf8");
  const audioCatalogSource = fs.readFileSync(require.resolve("../lib/audioCatalog.js"), "utf8");
  const seedAudioSource = fs.readFileSync(require.resolve("../scripts/seed-audio-library.js"), "utf8");
  const extractAudioSource = fs.readFileSync(require.resolve("../scripts/extract-audio-library.js"), "utf8");
  const packageSource = fs.readFileSync(require.resolve("../package.json"), "utf8");
  const videoPlayerSource = fs.readFileSync(require.resolve("../src/components/thegridcn/video-player.tsx"), "utf8");
  const waveformSource = fs.readFileSync(require.resolve("../src/components/thegridcn/waveform.tsx"), "utf8");
  const crtSource = fs.readFileSync(require.resolve("../src/components/thegridcn/crt-effect.tsx"), "utf8");
  const publicAudioPath = path.resolve(__dirname, "../public/audio");

  assert.match(localPageSource, /GamePageShell/);
  assert.match(localPageSource, /mode="local"/);
  assert.match(localPageSource, /showAccountMenu=\{false\}/);
  assert.match(localPageSource, /normalizeThemeShades/);
  assert.match(localPageSource, /localPlayerThemeShades=\{localPlayerThemeShades\}/);
  assert.match(legacyShellSource, /__reflexRoyaleLocalThemeShades/);
  assert.match(localRendererSource, /Chroma Sigil/);
  assert.match(localRendererSource, /role="tablist"/);
  assert.match(localRendererSource, /role="tab"/);
  assert.match(localRendererSource, /themeCommand/);
  assert.match(localRendererSource, /getCurrentLocalThemeCommand/);
  assert.match(localRendererSource, /getLocalPlayerThemePalette/);
  assert.match(localRendererSource, /player-slots--docked/);
  assert.match(localRendererSource, /_renderDockedPlayerSlots/);
  assert.match(localRendererSource, /announceMatchState\(true\)/);
  assert.match(localRendererSource, /announceMatchState\(false\)/);
  assert.match(gameCssSource, /online-host-controls/);
  assert.match(gameCssSource, /input-row--online-key-card/);
  assert.match(gameCssSource, /chroma-sigil-field:has\(\.chroma-sigil-panel:not\(\[hidden\]\)\)/);
  assert.match(gameCssSource, /lobby-form:has\(\.chroma-sigil-panel:not\(\[hidden\]\)\)/);
  assert.match(gameCssSource, /z-index: 2601/);
  assert.match(gameCssSource, /lobby--online-room #remotePlayerSlots/);
  assert.match(gameCssSource, /lobby--online-room #hostRosterControls/);
  assert.match(gameCssSource, /player-slot-dock--top-left/);
  assert.match(gameCssSource, /player-slot-dock--bottom-right/);
  assert.doesNotMatch(audioSource, /Play Again/);
  assert.match(localPaletteSource, /THEME_PROTOCOLS/);
  assert.match(localPaletteSource, /reflexRoyaleThemeCommand/);
  assert.match(localPaletteSource, /ui-lab-theme/);
  assert.match(localPaletteSource, /getCurrentLocalThemeCommand/);
  assert.match(localPaletteSource, /getLocalPlayerThemePalette/);
  assert.match(onlinePageSource, /GamePageShell/);
  assert.match(onlinePageSource, /mode="online"/);
  assert.match(onlinePageSource, /requireCurrentUser/);
  assert.match(shellSource, /GridBackground/);
  assert.doesNotMatch(shellSource, /AuthMenu/);
  assert.match(shellSource, /Mode/);
  assert.match(shellSource, /Legacy bridge/);
  assert.match(shellSource, /play-command-button/);
  assert.doesNotMatch(shellSource, /@\/components\/thegridcn\/button/);
  assert.doesNotMatch(shellSource, /max-w-\[min\(1500px,calc\(100vw-2rem\)\)\]/);
  assert.doesNotMatch(shellSource, /CardContent/);
  assert.doesNotMatch(shellSource, /@\/components\/thegridcn\/card/);
  assert.match(shellSource, /min-h-0/);
  assert.match(shellSource, /play-cockpit-shell/);
  assert.match(shellSource, /play-command-banner/);
  assert.match(shellSource, /play-command-banner__identity/);
  assert.match(shellSource, /play-command-banner__summary/);
  assert.match(shellSource, /play-command-banner__actions/);
  assert.match(shellSource, /play-command-banner__audio-slot/);
  assert.match(audioSource, /Dialog/);
  assert.match(audioSource, /VideoPlayer/);
  assert.match(audioSource, /Waveform/);
  assert.match(audioSource, /CRTEffect/);
  assert.match(audioSource, /audio-dialog__inline-progress/);
  assert.match(audioSource, /audio-dialog__hud-slider/);
  assert.match(audioSource, /audio-dialog__time-row/);
  assert.match(audioSource, /highFrequencyLift/);
  assert.match(audioSource, /Music From the Grid/);
  assert.doesNotMatch(audioSource, /Signal Waveform/);
  assert.doesNotMatch(audioSource, /Now Playing/);
  assert.match(audioSource, /AnalyserNode/);
  assert.match(audioSource, /createMediaElementSource/);
  assert.match(audioSource, /function ensureMusicSource/);
  assert.match(audioSource, /function attemptMusicPlayback/);
  assert.match(audioSource, /music\.muted = true/);
  assert.match(audioSource, /setAudioEnabled\(true\)/);
  assert.doesNotMatch(audioSource, /function readAudioEnabled/);
  assert.match(audioSource, /UI_SFX_ASSETS/);
  assert.doesNotMatch(audioSource, /new Audio\("\/audio\//);
  assert.match(audioLibSource, /UI_SFX_ASSETS/);
  assert.match(audioLibSource, /ui-click\.mp3/);
  assert.match(audioLibSource, /ui-hover\.mp3/);
  assert.equal(fs.existsSync(path.join(publicAudioPath, "ui-click.mp3")), true);
  assert.equal(fs.existsSync(path.join(publicAudioPath, "ui-hover.mp3")), true);
  assert.match(audioSource, /document\.addEventListener\("click", onClick\)/);
  assert.match(audioSource, /pointerover/);
  assert.match(audioSource, /playUiClick/);
  assert.match(audioSource, /playUiHover/);
  assert.match(audioSource, /UI_INTERACTION_SELECTOR/);
  assert.match(audioSource, /\[data-click-sound\]/);
  assert.match(audioSource, /lastClickAtRef/);
  assert.match(audioSource, /music\.src !== trackHref/);
  assert.match(audioSource, /void music\.play\(\)\.catch/);
  assert.match(audioSource, /if \(!track\) \{/);
  assert.match(audioSource, /if \(!audioEnabled\) \{/);
  assert.match(audioSource, /music\.pause\(\);\s+return;\s+}\s+if \(music\.src !== new URL\(track, window\.location\.origin\)\.href\)/);
  assert.match(audioSource, /fetchAudioPlaylist/);
  assert.match(audioSource, /activeTrack\.sources\.length/);
  assert.match(audioSource, /audio-dialog__track-list/);
  assert.match(audioSource, /audio-dialog__track-search/);
  assert.match(audioSource, /audio-dialog__track-filters/);
  assert.match(audioSource, /audio-dialog__track-scroller/);
  assert.match(audioSource, /audio-dialog__mix-field/);
  assert.match(audioSource, /Master Volume/);
  assert.match(audioSource, /function VolumeSlider/);
  assert.doesNotMatch(audioSource, /const VolumeSlider =/);
  assert.match(audioSource, /AUDIO_MIX_MODE_KEY/);
  assert.match(audioSource, /AUDIO_MATCH_STATE_EVENT/);
  assert.match(audioSource, /AUDIO_TRACK_LOOP_KEY/);
  assert.match(audioSource, /resolveMixCategory/);
  assert.match(audioSource, /matchInProgress \? "battle" : "lobby"/);
  assert.match(audioSource, /currentMixSignatureRef/);
  assert.match(audioSource, /appliedCustomTrackIdRef/);
  assert.match(audioSource, /pickRandomTrackIndexExcept/);
  assert.match(audioSource, /mode !== "custom"/);
  assert.match(audioSource, /music\.loop = false/);
  assert.match(audioSource, /music\.addEventListener\("ended", onEnded\)/);
  assert.match(audioSource, /trackLoopEnabled/);
  assert.match(audioSource, /pickRandomTrackIndex/);
  assert.doesNotMatch(audioSource, /Change Track/);
  assert.doesNotMatch(audioSource, /Source Timestamp/);
  assert.doesNotMatch(audioSource, /Open source video/);
  const remoteSource = fs.readFileSync(require.resolve("../public/js/remote.js"), "utf8");
  assert.match(remoteSource, /function renderThemePickerField/);
  assert.match(remoteSource, /selectedEntryRoundCount/);
  assert.match(remoteSource, /totalRounds: selectedEntryRoundCount/);
  assert.match(remoteSource, /claim a Chroma Sigil/);
  assert.match(remoteSource, /round-slider--create/);
  assert.match(remoteSource, /const hostRoundControls = isHost \?/);
  assert.match(remoteSource, /\$\{hostRoundControls\}/);
  assert.match(remoteSource, /lobby lobby--online-room/);
  assert.match(remoteSource, /player-slots--docked/);
  assert.match(remoteSource, /function renderDockedRoster/);
  assert.match(remoteSource, /\$\{isHost \? `<div class="lobby-layout-bottom"><button id="startGameBtn"/);
  assert.doesNotMatch(remoteSource, /<aside class="online-host-controls"/);
  assert.match(remoteSource, /announceMatchState\(true\)/);
  assert.match(remoteSource, /announceMatchState\(false\)/);
  assert.match(audioSource, /play-command-banner__audio-slot/);
  assert.match(audioLibSource, /AUDIO_PLAYLIST/);
  assert.match(audioLibSource, /category: "lobby"/);
  assert.match(audioLibSource, /category: "battle"/);
  assert.match(audioLibSource, /AUDIO_MIX_MODE_KEY/);
  assert.match(audioLibSource, /AUDIO_CUSTOM_TRACK_KEY/);
  assert.match(audioLibSource, /AUDIO_MATCH_STATE_EVENT/);
  assert.match(audioLibSource, /AUDIO_TRACK_LOOP_KEY/);
  assert.match(audioLibSource, /Flower Fields/);
  assert.match(audioLibSource, /Athena IV/);
  assert.match(audioLibSource, /durationSeconds: 360/);
  assert.match(audioLibSource, /Break What You Must/);
  assert.match(audioLibSource, /Destiny 2/);
  assert.match(audioLibSource, /durationSeconds: 296/);
  assert.match(audioLibSource, /Mirror's Edge/);
  assert.match(audioLibSource, /Future セルフ/);
  assert.match(audioLibSource, /Peace of Mind Before Death/);
  assert.match(audioLibSource, /thumbnailImage/);
  assert.match(audioCatalogSource, /requestedTrack/);
  assert.match(audioCatalogSource, /extractStartSeconds: 7122/);
  assert.match(audioCatalogSource, /extractStartSeconds: 8137/);
  assert.match(audioCatalogSource, /maxExtractSeconds: 360/);
  assert.match(audioLibSource, /\/audio\/break-what-you-must\.mp3/);
  assert.match(audioLibSource, /\/audio\/break-what-you-must\.webm/);
  assert.match(audioLibSource, /\/audio\/flower-fields\.mp3/);
  assert.match(audioLibSource, /\/audio\/flower-fields\.webm/);
  assert.match(audioLibSource, /flower-fields-cover\.webp/);
  assert.match(audioLibSource, /youtube\.com\/watch\?v=J4njTYvvENQ&t=8137s/);
  assert.match(audioRoutesSource, /router\.get\("\/tracks"/);
  assert.match(audioRoutesSource, /category/);
  assert.match(audioRoutesSource, /thumbnailImage/);
  assert.match(audioRoutesSource, /dbTracksById/);
  assert.match(audioRoutesSource, /updatedAt/);
  assert.match(audioRoutesSource, /\/tracks\/:trackId\/stream/);
  assert.match(audioRoutesSource, /Accept-Ranges/);
  assert.match(audioModelSource, /variants/);
  assert.match(audioModelSource, /category/);
  assert.match(audioModelSource, /thumbnailImage/);
  assert.match(audioModelSource, /data: \{/);
  assert.match(audioCatalogSource, /category: "lobby"/);
  assert.match(audioCatalogSource, /category: "battle"/);
  assert.match(audioCatalogSource, /catalogTrack\?\.category/);
  assert.match(audioCatalogSource, /audioSourceVersion/);
  assert.match(audioCatalogSource, /appendSourceVersion/);
  assert.match(audioCatalogSource, /FLOWER_FIELDS_TRACK_ID/);
  assert.match(seedAudioSource, /AudioTrack\.findOneAndUpdate/);
  assert.match(seedAudioSource, /ALLOW_MISSING_AUDIO/);
  assert.match(packageSource, /audio:extract/);
  assert.match(extractAudioSource, /CONFIRM_AUDIO_RIGHTS/);
  assert.match(videoPlayerSource, /data-slot="video-player"/);
  assert.match(videoPlayerSource, /onToggleLoop/);
  assert.match(videoPlayerSource, /aria-pressed=\{loopEnabled\}/);
  assert.match(videoPlayerSource, /relative aspect-video overflow-hidden/);
  assert.match(videoPlayerSource, /bottom-3 left-3/);
  assert.doesNotMatch(videoPlayerSource, /bottom-14/);
  assert.match(audioSource, /alt=\{`\$\{activeTrack\.title\} cover frame`\}/);
  assert.match(waveformSource, /data-slot="tron-waveform"/);
  assert.match(waveformSource, /levels\?: number\[\]/);
  assert.match(waveformSource, /fill\?: boolean/);
  assert.doesNotMatch(waveformSource, /border-primary\/30/);
  assert.doesNotMatch(waveformSource, /repeating-linear-gradient/);
  assert.match(crtSource, /CRTEffect/);
  assert.doesNotMatch(shellSource, /bg-background\/70/);
  assert.doesNotMatch(shellSource, /bg-card\/45/);
  assert.match(shellSource, /game-shell-stage/);
  assert.match(shellSource, /game-hud-frame/);
  assert.match(legacyShellSource, /showAccountMenu = true/);
  assert.match(buttonSource, /transition-\[background-color,color,border-color,box-shadow,transform\] duration-500/);
  assert.match(buttonSource, /border-2 !border-primary !bg-transparent !text-primary hover:!bg-primary hover:!text-primary-foreground/);
  assert.doesNotMatch(buttonSource, /hover:shadow-\[0_0_24px_color-mix/);
  assert.match(buttonSource, /active:translate-y-px/);
  assert.doesNotMatch(buttonSource, /before:scale-x-0/);
  assert.match(buttonSource, /rounded-none/);
  assert.match(buttonSource, /data-slot="button"/);
  assert.doesNotMatch(buttonSource, /playUiClick/);
  const localLegacySource = fs.readFileSync(require.resolve("../public/js/UIRenderer.js"), "utf8");
  const remoteLegacySource = fs.readFileSync(require.resolve("../public/js/remote.js"), "utf8");
  const keyMapSource = fs.readFileSync(require.resolve("../public/js/keyMap.js"), "utf8");
  const sliderSource = fs.readFileSync(require.resolve("../src/components/thegridcn/slider.tsx"), "utf8");
  assert.match(sliderSource, /@radix-ui\/react-slider/);
  assert.match(sliderSource, /data-slot="slider"/);
  assert.match(sliderSource, /data-slot="slider-track"/);
  assert.match(sliderSource, /data-slot="slider-range"/);
  assert.match(sliderSource, /data-slot="slider-thumb"/);
  assert.match(sliderSource, /size-4/);
  assert.match(gameCssSource, /--round-slider-accent: var\(--primary/);
  assert.doesNotMatch(gameCssSource, /#ffd000/);
  assert.match(localLegacySource, /type="range"/);
  assert.match(localLegacySource, /holoKeyboardMount/);
  assert.match(localLegacySource, /renderHolographicKeyboard/);
  assert.match(localLegacySource, /normalizeGameKey/);
  assert.match(localLegacySource, /dragstart/);
  assert.match(localLegacySource, /movePlayerKey/);
  assert.match(localLegacySource, /round-slider/);
  assert.match(localLegacySource, /roundCountValue/);
  assert.match(remoteLegacySource, /type="range"/);
  assert.match(remoteLegacySource, /holoKeyboardMount/);
  assert.match(remoteLegacySource, /renderHolographicKeyboard/);
  assert.match(remoteLegacySource, /normalizeGameKey/);
  assert.match(remoteLegacySource, /dragstart/);
  assert.match(remoteLegacySource, /bindKey/);
  assert.match(remoteLegacySource, /round-slider--host/);
  assert.match(remoteLegacySource, /roundCountInputValue/);
  assert.match(remoteLegacySource, /btn-go/);
  assert.match(keyMapSource, /holo-keyboard-panel/);
  assert.match(keyMapSource, /KEYBOARD_ROWS/);
  const globalsSource = fs.readFileSync(require.resolve("../src/app/globals.css"), "utf8");
  const gameShellStylesSource = fs.readFileSync(require.resolve("../src/app/game-shell.css"), "utf8");
  assert.match(globalsSource, /aspect-ratio: 16 \/ 9/);
  assert.match(globalsSource, /\.audio-dialog__album-art \{[\s\S]*width: 100%;[\s\S]*height: 100%;/);
  assert.doesNotMatch(globalsSource, /transform: scale\(1\.18\)/);
  assert.doesNotMatch(globalsSource, /min-height: 320px/);
  assert.match(globalsSource, /\.\/game-shell\.css/);
  assert.doesNotMatch(globalsSource, /\.play-cockpit-shell/);
  assert.match(gameShellStylesSource, /\.play-cockpit-shell/);
  assert.match(gameShellStylesSource, /\.play-command-banner/);
  assert.match(gameShellStylesSource, /\.play-command-button/);
  assert.match(gameShellStylesSource, /\.play-command-button:hover/);
  assert.match(gameShellStylesSource, /grid-template-columns: auto minmax\(16rem, 1fr\) auto/);
  assert.match(gameShellStylesSource, /\.game-hud-frame/);
  assert.match(gameShellStylesSource, /margin-inline: clamp/);
  assert.match(gameShellStylesSource, /game-hud-frame__content/);
  assert.match(gameShellStylesSource, /container-type: size/);
  assert.match(gameShellStylesSource, /aspect-ratio: 16 \/ 9/);
  assert.match(gameShellStylesSource, /width: min\(100cqw, calc\(100cqh \* 16 \/ 9\)\)/);
  assert.match(gameCssSource, /#game-root \.btn:focus-visible/);
  assert.match(gameCssSource, /#game-root \.btn-remove:focus-visible/);
  assert.match(gameCssSource, /\.holo-keyboard-panel/);
  assert.match(gameCssSource, /\.holo-key--bound/);
  assert.match(gameCssSource, /\.holo-key--ready/);
  assert.match(gameCssSource, /\.holo-key--dragging/);
  assert.match(gameCssSource, /\.holo-key--drop-target/);
  assert.match(gameCssSource, /box-shadow 500ms ease/);
  assert.match(gameCssSource, /0 0 38px color-mix\(in oklch, var\(--primary/);
  assert.match(gameCssSource, /translateY\(1px\)/);
  assert.match(tabsSource, /active:translate-y-px/);
  assert.match(gameCssSource, /Legacy-mounted game surface/);
  assert.match(gameCssSource, /#game-root/);
  assert.match(gameCssSource, /height: 100%/);
  assert.match(gameCssSource, /#game-root \.arena,/);
  assert.match(gameCssSource, /#game-root \.arena-solo/);
  assert.match(gameCssSource, /font-family: var\(--font-orbitron\)/);
});

test("auth pages prevent credential query-string fallback", () => {
  const authPageSource = fs.readFileSync(require.resolve("../src/components/app/auth-page.tsx"), "utf8");
  const scriptSource = fs.readFileSync(require.resolve("../public/script.js"), "utf8");
  const authRouteSource = fs.readFileSync(require.resolve("../routes/auth.js"), "utf8");

  assert.match(authPageSource, /method="post"/);
  assert.match(authPageSource, /action=\{mode === "signup" \? "\/api\/auth\/signup" : "\/api\/auth\/login"\}/);
  assert.match(authPageSource, /minLength=\{3\}/);
  assert.match(authPageSource, /maxLength=\{20\}/);
  assert.match(authPageSource, /pattern="\[A-Za-z0-9_-\]\+"/);
  assert.match(authPageSource, /minLength=\{8\}/);
  assert.match(scriptSource, /USERNAME_PATTERN/);
  assert.match(scriptSource, /MIN_PASSWORD_LENGTH/);
  assert.match(authRouteSource, /USERNAME_PATTERN/);
  assert.match(authRouteSource, /Password must be at least 8 characters/);
  assert.match(authRouteSource, /That username is already taken/);
});
